### PR TITLE
dumbass portal animation took me 3 hours for just 11 frames dude. 

### PR DESCRIPTION
**Pull request by jarexgonz**
- Modified the spawn location of player to center it at the top of the stairs
- Animation will play once when the game is boot up, not after game overs.

I noticed that the dimensions of the player change after game over, this is probably a bug but I did not want to risk fixing it and break 20 other stuff so i just made it not replay the animation after game over so it wouldnt look weird.

### CODE REVIEW

**Comment by jplnb** [comment]
looks like you manually updated the bounds json, I'll update the bounds image later today on this branch so that the new spawn location doesn't go away if you regen the json.

**Comment by jplnb** [comment]
inconsistent character sizes are probably caused by the player first being 51x24 or whatever with respect to bgImage size, but then there immediately is a resize to the window size. Later on game restarts, player box is created as 51x24 with respect to true window size. Can probably fix by scaling initial hitbox size to reflect the current arena width/height first.

**Comment by jplnb** [comment]
you're also hardcoding x and y values for the portal animation in Arena, which breaks on browsers using different resolutions than the one you wrote it for

20241207_18h17m22s_grim

**Comment by jplnb** [comment]
fixed everything, @jay6o please review

**Review by jay6o — APPROVED** [review]

**Pull request merged**
